Repository tidy-finance/r-tidyfinance, pull requests merged in 2024-08, with the labels that each got.

#68 Added function to estimate Fama-MacBeth
  DESCRIPTION
  NAMESPACE
  R/estimate_fama_macbeth.R
  R/tidyfinance-package.R
  man/estimate_fama_macbeth.Rd
  tests/testthat/test-estimate_fama_macbeth.R
Labels: enhancement

#70 Added function to estimate betas
  DESCRIPTION
  NAMESPACE
  R/estimate_betas.R
  R/estimate_model.R
  R/global_variables.R
  R/tidyfinance-package.R
  man/estimate_betas.Rd
  man/estimate_model.Rd
  tests/testthat/test-estimate_betas.R
  tests/testthat/test-estimate_model.R
Labels: enhancement

#76 Removed redundant check_if_package_installed function
  R/check_if_package_installed.R
  R/disconnect_connection.R
  R/download_data_factors.R
  R/download_data_stocks.R
  R/download_data_wrds_ccm_links.R
  R/download_data_wrds_clean_trace.R
  R/download_data_wrds_compustat.R
  R/download_data_wrds_crsp.R
  R/download_data_wrds_fisd.R
  R/estimate_fama_macbeth.R
  R/get_wrds_connection.R
  man/check_if_package_installed.Rd
Labels: enhancement

#79 Added progress bars using cli
  R/download_data_stocks.R
  R/download_data_wrds_crsp.R
Labels: enhancement

#75 Introduced Period object as lookback parameter in estimate_betas
  R/estimate_betas.R
  R/estimate_model.R
  man/estimate_betas.Rd
  tests/testthat/test-estimate_betas.R
  tests/testthat/test-estimate_model.R
Labels: enhancement

#73 Added functions to calculate portfolio returns
  NAMESPACE
  R/assign_portfolio.R
  R/breakpoint_options.R
  R/compute_breakpoints.R
  R/compute_long_short_returns.R
  R/compute_portfolio_returns.R
  R/global_variables.R
  R/tidyfinance-package.R
  man/assign_portfolio.Rd
  man/breakpoint_options.Rd
  man/compute_breakpoints.Rd
  man/compute_long_short_returns.Rd
  man/compute_portfolio_returns.Rd
  tests/testthat/test-assign_portfolio.R
  vignettes/using-tidyfinance.Rmd
Labels: enhancement

#86 Update download_data.R
  R/download_data.R
Labels: bug

#91 Added links to breakpoin_options in Rd files
  R/compute_breakpoints.R
  R/compute_portfolio_returns.R
  man/compute_breakpoints.Rd
  man/compute_portfolio_returns.Rd
Labels: enhancement

#92 Added support for downloading open source asset pricing factor data
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/download_data.R
  R/download_data_osap.R
  R/list_supported_types.R
  man/download_data_osap.Rd
Labels: enhancement

#93 Added get_random_user_agent()
  R/download_data_constituents.R
  R/download_data_fred.R
  R/download_data_stocks.R
  R/get_random_user_agent.R
  man/get_random_user_agent.Rd
Labels: enhancement

#94 Added download_data_symbols()
  NAMESPACE
  R/download_data.R
  R/download_data_symbols.R
  R/global_variables.R
  R/list_supported_types.R
  man/download_data.Rd
  man/download_data_symbols.Rd
Labels: enhancement

#96 Inferred proper symbols with country codes from index constituents
  DESCRIPTION
  NAMESPACE
  R/download_data.R
  R/download_data_constituents.R
  R/download_data_stock_prices.R
  R/list_supported_types.R
  man/download_data.Rd
  man/download_data_stock_prices.Rd
  man/download_data_stocks.Rd
  man/list_supported_types_stocks.Rd
Labels: enhancement

#98 Fixed bug with adjusted close prices in download_data_stocks()
  R/download_data_stock_prices.R
Labels: bug

#97 Remove hard-coded column name requirements
  NAMESPACE
  R/assign_portfolio.R
  R/breakpoint_options.R
  R/compute_breakpoints.R
  R/compute_long_short_returns.R
  R/compute_portfolio_returns.R
  R/data_options.R
  R/download_data_constituents.R
  R/download_data_fred.R
  R/download_data_osap.R
  R/download_data_stock_prices.R
  R/download_data_symbols.R
  R/estimate_betas.R
  R/estimate_fama_macbeth.R
  R/estimate_model.R
  R/get_random_user_agent.R
  R/get_wrds_connection.R
  R/global_variables.R
  R/lag_column.R
  R/list_tidy_finance_chapters.R
  R/open_tidy_finance_website.R
  R/tidyfinance-package.R
  R/trim.R
  R/winsorize.R
  man/assign_portfolio.Rd
  man/breakpoint_options.Rd
  man/compute_breakpoints.Rd
  man/compute_long_short_returns.Rd
  man/compute_portfolio_returns.Rd
  man/data_options.Rd
  man/download_data_constituents.Rd
  man/download_data_fred.Rd
  man/download_data_osap.Rd
  man/download_data_stock_prices.Rd
  man/download_data_symbols.Rd
  man/estimate_betas.Rd
  man/estimate_fama_macbeth.Rd
  man/estimate_model.Rd
  man/get_random_user_agent.Rd
  man/lag_column.Rd
  man/list_tidy_finance_chapters.Rd
  man/open_tidy_finance_website.Rd
  man/trim.Rd
  man/winsorize.Rd
  tests/testthat/test-estimate_fama_macbeth.R
Labels: enhancement

#100 Fixed bug with parsing in download_data_macro_predictors()
  DESCRIPTION
  R/download_data_macro_predictors.R
  man/download_data_macro_predictors.Rd
Labels: bug

#101 Released tidyfinance 0.4.0
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/download_data.R
  R/download_data_stock_prices.R
  R/download_data_symbols.R
  R/lag_column.R
  R/list_supported_types.R
  README.Rmd
  README.md
  man/download_data.Rd
  man/download_data_symbols.Rd
  man/lag_column.Rd
  man/list_supported_types_q.Rd
Labels: release

#106 Added missing support of "wrds_trace_enhanced" and "wrds_fisd" support to `download_data_wrds()`
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/download_data.R
  R/download_data_wrds.R
  R/download_data_wrds_trace_enhanced.R
  R/list_supported_types.R
  man/download_data_wrds.Rd
  man/download_data_wrds_trace_enhanced.Rd
Labels: bug

#107 Added intercept to `estimate_model()`, `estimate_betas()`, and `estimate_fama_macbeth()`
  DESCRIPTION
  NEWS.md
  R/estimate_betas.R
  R/estimate_model.R
  man/estimate_model.Rd
  tests/testthat/test-estimate_fama_macbeth.R
  tests/testthat/test-estimate_model.R
Labels: bug

#108 Added `vcov_options` parameter to `estimate_fama_macbeth()`
  DESCRIPTION
  NEWS.md
  R/estimate_fama_macbeth.R
  man/estimate_fama_macbeth.Rd
Labels: enhancement
