Repository tidy-finance/r-tidyfinance, pull requests merged in 2024-07, with the labels that each got.

#21 Removed mkt_excess from download_data_wrds_crsp() output
  R/download_data_wrds_crsp.R
Labels: bug

#25 Replaced ... with additional_columns parameter for CRSP and Compustat download
  R/download_data_macro_predictors.R
  R/download_data_wrds_clean_trace.R
  R/download_data_wrds_compustat.R
  R/download_data_wrds_crsp.R
  man/download_data_macro_predictors.Rd
  man/download_data_wrds_clean_trace.Rd
  man/download_data_wrds_compustat.Rd
  man/download_data_wrds_crsp.Rd
Labels: bug, enhancement

#26 22 in download x functions make types more accessible
  R/check_supported_type.R
  R/list_supported_types.R
Labels: documentation, enhancement

#32 29 crsp daily add support for columns in msenames v1 and stksecurityinfohist v2
  R/download_data_wrds_crsp.R
Labels: enhancement

#31 30 support in download data factors ff to access all available files
  DESCRIPTION
  R/download_data.R
  R/download_data_factors.R
  R/download_data_wrds_crsp.R
  R/list_supported_types.R
  README.Rmd
  README.md
  man/download_data.Rd
  man/download_data_factors.Rd
  man/download_data_factors_ff.Rd
  vignettes/using-tidyfinance.Rmd
Labels: enhancement

#38 Make start_date and end_date optional in `download_data() `
  R/download_data.R
  R/download_data_factors.R
  R/download_data_macro_predictors.R
  R/download_data_wrds.R
  R/download_data_wrds_clean_trace.R
  R/download_data_wrds_compustat.R
  R/download_data_wrds_crsp.R
  R/download_data_wrds_fisd.R
  R/list_supported_types.R
  man/download_data.Rd
  man/download_data_factors.Rd
  man/download_data_factors_ff.Rd
  man/download_data_factors_q.Rd
  man/download_data_macro_predictors.Rd
  man/download_data_wrds.Rd
  man/download_data_wrds_clean_trace.Rd
  man/download_data_wrds_compustat.Rd
  man/download_data_wrds_crsp.Rd
Labels: enhancement

#39 ci: use r-cmd-check GHA
  .github/workflows/R-CMD-check.yaml
  README.Rmd
  README.md
Labels: enhancement

#43 align date columns for CRSP and Compustat
  .Rbuildignore
  .github/workflows/R-CMD-check.yaml
  .gitignore
  DESCRIPTION
  NAMESPACE
  R/download_data.R
  R/download_data_factors.R
  R/download_data_macro_predictors.R
  R/download_data_wrds.R
  R/download_data_wrds_clean_trace.R
  R/download_data_wrds_compustat.R
  R/download_data_wrds_crsp.R
  R/download_data_wrds_fisd.R
  R/global_variables.R
  man/download_data.Rd
  man/download_data_factors.Rd
  man/download_data_factors_ff.Rd
  man/download_data_factors_q.Rd
  man/download_data_macro_predictors.Rd
  man/download_data_wrds.Rd
  man/download_data_wrds_clean_trace.Rd
  man/download_data_wrds_compustat.Rd
  man/download_data_wrds_crsp.Rd
  man/download_data_wrds_fisd.Rd
  vignettes/dates-in-tidyfinance.Rmd
Labels: enhancement

#46 Add filter for quarterly compustat
  DESCRIPTION
  R/download_data_wrds_compustat.R
Labels: bug

#47 refactor: don't use getNamespace for getting function name
  R/disconnect_connection.R
  R/download_data_factors.R
  R/download_data_macro_predictors.R
  R/download_data_stocks.R
  R/download_data_wrds_ccm_links.R
  R/download_data_wrds_clean_trace.R
  R/download_data_wrds_compustat.R
  R/download_data_wrds_crsp.R
  R/download_data_wrds_fisd.R
  R/get_wrds_connection.R
Labels: enhancement

#48 refactor: unified importing
  DESCRIPTION
  NAMESPACE
  R/check_if_package_installed.R
  R/create_summary_statistics.R
  R/create_wrds_dummy_database.R
  R/download_data_factors.R
  R/download_data_macro_predictors.R
  R/download_data_stocks.R
  R/download_data_wrds_ccm_links.R
  R/download_data_wrds_clean_trace.R
  R/download_data_wrds_compustat.R
  R/download_data_wrds_crsp.R
  R/download_data_wrds_fisd.R
  R/estimate_model.R
  R/list_supported_types.R
  R/open_tidy_finance_website.R
  R/tidyfinance-package.R
  R/trim.R
  R/winsorize.R
  man/download_data_factors_ff.Rd
  man/download_data_factors_q.Rd
  man/download_data_macro_predictors.Rd
  man/download_data_stocks_yf.Rd
  man/download_data_wrds_ccm_links.Rd
  man/download_data_wrds_crsp.Rd
  vignettes/using-tidyfinance.Rmd
Labels: enhancement

#52 Added support for legacy Fama-French data types
  R/check_supported_type.R
  R/list_supported_types.R
  man/list_supported_types_ff_legacy.Rd
Labels: enhancement

#57 Removed dependency on named placeholder from R 4.2
  R/download_data_factors.R
Labels: bug

#56 refactor: migrate to cli
  DESCRIPTION
  R/assign_portfolio.R
  R/check_supported_type.R
  R/create_summary_statistics.R
  R/create_wrds_dummy_database.R
  R/download_data_factors.R
  R/download_data_macro_predictors.R
  R/download_data_stocks.R
  R/download_data_wrds_clean_trace.R
  R/download_data_wrds_compustat.R
  R/download_data_wrds_crsp.R
  R/estimate_model.R
  R/get_wrds_connection.R
  R/set_wrds_credentials.R
  R/trim.R
  R/winsorize.R
  man/assign_portfolio.Rd
  tests/testthat/test-assign_portfolio.R
Labels: enhancement

#63 refactor: remove explicit return at the end of functions
  R/assign_portfolio.R
  R/create_wrds_dummy_database.R
  R/download_data_wrds_compustat.R
Labels: enhancement

#65 refactor: use NULL as a default value for optional args
  DESCRIPTION
  R/create_summary_statistics.R
  R/download_data.R
  R/download_data_factors.R
  R/download_data_macro_predictors.R
  R/download_data_stocks.R
  R/download_data_wrds.R
  R/download_data_wrds_clean_trace.R
  R/download_data_wrds_compustat.R
  R/download_data_wrds_crsp.R
  man/download_data.Rd
  man/download_data_factors.Rd
  man/download_data_factors_ff.Rd
  man/download_data_factors_q.Rd
  man/download_data_macro_predictors.Rd
  man/download_data_stocks.Rd
  man/download_data_stocks_yf.Rd
  man/download_data_wrds.Rd
  man/download_data_wrds_clean_trace.Rd
  man/download_data_wrds_compustat.Rd
  man/download_data_wrds_crsp.Rd
  man/tidyfinance-package.Rd
Labels: enhancement

#67 Updated macro predictors and q factors to end of 2023 data
  DESCRIPTION
  NAMESPACE
  R/download_data_factors.R
  R/download_data_macro_predictors.R
  R/global_variables.R
  R/tidyfinance-package.R
  man/download_data_factors_q.Rd
  man/download_data_macro_predictors.Rd
Labels: enhancement
